### ISSUE TITLE
404 issue calling-a-subroutine-from-a-dictionary-item

### ISSUE THREAD

**Issue by calebjeffery** [zumasys/docs#23]
Missing Documentation for https://docs.zumasys.com/jbase/calling-a-subroutine-from-a-dictionary-item

**Comment by ryannmedina** [comment]
Where is the link the that took you there?

Thanks for the heads up @calebjeffery!

**Comment by calebjeffery** [comment]
Hi Ryan, here is the link that contains the broken link 
https://docs.zumasys.com/jbase/conversion-processing/b-conversion/

**Comment by calebjeffery** [comment]
Just found what is missing here is the what the link should be
https://docs.zumasys.com/jbase/jql/calling-a-subroutine-from-a-dictionary-item/

**Comment by itsxallwater** [comment]
Thanks @calebjeffery! Just pushed a fix in https://github.com/zumasys/docs/commit/45c54304a31438b0e0ff0fbbe54523d21b2028ae. Docs are rebuilding and redeploying now.
